title: GL552JX Homelab
language: en
theme: dark
color: gray
target: _self
headerStyle: clean
statusStyle: "dot"
hideVersion: true
disableCollapse: true
useEqualHeights: true
cardBlur: xl
favicon: https://raw.githubusercontent.com/walkxcode/dashboard-icons/refs/heads/main/png/homelab.png

layout:
  Infrastructure:
    icon: mdi-server
    style: column
  Services:
    icon: mdi-docker
    style: column
  Phone (Tailscale):
    icon: mdi-cellphone
    style: column
