arch: amd64
cores: 1
hostname: caddy
memory: 128
net0: name=eth0,bridge=vmbr0,gw=192.168.1.1,hwaddr=BC:24:11:6D:60:57,ip=192.168.1.254/24,type=veth
net1: name=eth1,bridge=svcnet,hwaddr=BC:24:11:DA:A4:50,ip=dhcp,type=veth
ostype: debian
rootfs: local-lvm:vm-103-disk-0,size=2G
swap: 0
unprivileged: 1
